/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package newpackage;
import java.io.*;
import java.security.NoSuchAlgorithmException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author npadm
 */
public class Main extends javax.swing.JFrame{


    private int userNum = 0; 
    PassEncrypt encrypter = new PassEncrypt();

    /**
     * Creates new form Main
     */
    public Main() throws FileNotFoundException{
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() throws FileNotFoundException{

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtuser = new javax.swing.JTextField();
        jpassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        blogin = new javax.swing.JButton();
        jcshow_password = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 13, 26));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        jPanel1.setLayout(null); 

        jLabel1.setBackground(new java.awt.Color(229, 229, 243));
        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        jLabel1.setText("LOGIN");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(270, 20, 130, 80);
        // new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 130, 80)

        jtuser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jtuser);
        jtuser.setBounds(200, 90, 270, 50);
        //, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 270, 50)

        jpassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jpassword);
        jpassword.setBounds(200, 170, 270, 50);
        //, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 270, 50)
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 120, -1, -1);
        //, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1)

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel3.setText("username");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 110, 100, 20);
        //, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 100, 20)

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel4.setText("password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 180, 110, 20);
        //, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 110, 20)

        blogin.setText("login");
        jPanel1.add(blogin);
        blogin.setBounds(270, 290, 120, 30);
        blogin.addActionListener(new java.awt.event.ActionListener() { // <------
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            try
            {
                bloginActionPerformed(evt);
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
        });

        jcshow_password.setText("Show Password");
        jcshow_password.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
                try
                {
                    jcshow_passwordActionPerformed(evt);
                }
                catch(Exception e)
                {
                    System.out.println(e);
                }
            }
        });
        jPanel1.add(jcshow_password);
        jcshow_password.setBounds(490, 190, -1, -1);
        //, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1)

        jButton1.setText("Forgot Password");
        jPanel1.add(jButton1);
        jButton1.setBounds(270, 240, 135, 30);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            try
            {
                jButton1ActionPerformed(evt);
            }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void bloginActionPerformed(java.awt.event.ActionEvent evt) throws FileNotFoundException, NoSuchAlgorithmException{                                       
        // TODO add your handling code here:
        ArrayList<String> emails = new ArrayList<String>();
        ArrayList<String> passwords = new ArrayList<String>();
        String password;
        boolean isTrue = true;


        File file1 = new File("emails.txt");
        Scanner reader = new Scanner(file1);

        while(reader.hasNextLine())
        {
            emails.add(reader.nextLine());
        }
        reader.close();
        File file2 = new File("passwords.txt"); 
        Scanner reader1 = new Scanner(file2); 

        while(reader1.hasNextLine())
        {
            passwords.add(reader1.nextLine());
        }

        reader1.close();
        
        String u = jtuser.getText();
        String p = jpassword.getText();
        boolean verified = false;

        for(int i = 0; i < emails.size(); i++)
        {
            if(u.equals(emails.get(i)) && encrypter.encrypt(p).equals(passwords.get(i)))
            {
                JOptionPane.showMessageDialog(null, "Login Successful");
                System.out.println("test");
                nextScreen(jtuser.getText());
                break;
            }
            else if(jtuser.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Please fill out username");
            }
            else if(jpassword.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Please fill out password");
            }
            else if(i == emails.size() - 1 && !(u.equals(emails.get(i))))
            {
                JOptionPane.showMessageDialog(null, "Incorrect Login");
            }
        }
    }           
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws IOException, FileNotFoundException, NoSuchAlgorithmException{                                       
        File messageFile = new File("message.txt");
        FileWriter message = new FileWriter(messageFile);
        message.write("One of your emplyees has forgotten their password!");
        message.close();
        JOptionPane.showMessageDialog(null, "A message has been sent to your supervisor. They will contact you soon!");
    }                     

    private void jcshow_passwordActionPerformed(java.awt.event.ActionEvent evt) throws FileNotFoundException{                                                
        // TODO add your handling code here:
        if(jcshow_password.isSelected()){
            jpassword.setEchoChar((char)0);
        }
        else{
            jpassword.setEchoChar(('*'));
        }
    }   

    public void nextScreen(String email) { 

        UserWeeklySchedule normalUserGUI; 
        AdminWeeklySchedule adminGUI; 

        //if user is admin 
        if (email.equals("ezstop2923@yahoo.com")) {

            //closes current frame, which is the login window 
            setVisible(false);

            //opens the next frame, which is the admin weekly schedule gui
            adminGUI = new AdminWeeklySchedule();
            adminGUI.setVisible(true);
            
        } 
        //if user is not admin
        else {

            //closes current frame, which is the login window 
            setVisible(false);

            //opens the next frame, which is the normal user weekly schedule gui
            normalUserGUI = new UserWeeklySchedule();
            normalUserGUI.setVisible(true);
            
        }

    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
                try
                {
                    new Main().setVisible(true);
                }
                catch(Exception e)
                {
                    System.out.println(e);
                }
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton blogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel logoJlabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jcshow_password;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JTextField jtuser;

    //for the logo
    //private javax.swing.JLabel logo; 
    //private ImageIcon logo = new ImageIcon(this.class.getResource("logo.png")); //the image for the logo
    // End of variables declaration                   
}
